"""EURUSD bounded-observer reality model.

This module is deliberately instrument-specific: its parameters are not shared with
XAUUSD, so the decision layer cannot operate until both models have produced state.
"""
from __future__ import annotations

from dataclasses import dataclass, asdict
from math import log, sqrt
from typing import Optional


@dataclass
class RealityState:
    instrument: str
    estimate: float = 0.0
    return_mean: float = 0.0
    volatility: float = 1e-6
    change_score: float = 0.0
    detected: bool = False
    alpha: float = 0.10
    integration_window: float = 20.0
    gain: float = 1.0
    criterion: float = 2.5
    evidence: float = 0.0
    samples: int = 0

    def to_dict(self) -> dict:
        return asdict(self)


class EURUSDRealityModel:
    """Adaptive state estimator for EURUSD bars.

    The model uses a recursive estimate (UE), volatility-normalized innovation
    detection (SG/FT), and reset-on-detection memory. It is a research model, not
    a claim that market prices are literally generated by this state machine.
    """

    def __init__(self, state: Optional[dict] = None):
        self.state = RealityState(**state) if state else RealityState(instrument="EURUSD")
        self.prev_close: Optional[float] = None
        self.prev_estimate: Optional[float] = None
        self.last_observation: Optional[float] = None

    def update(self, close: float, high: float, low: float) -> RealityState:
        if close <= 0 or high <= 0 or low <= 0:
            raise ValueError("EURUSD prices must be positive")
        if self.prev_close is None:
            self.prev_close = close
            self.prev_estimate = close
            self.state.estimate = close
            self.state.samples = 1
            return self.state

        ret = log(close / self.prev_close)
        true_range = max(high - low, abs(high - self.prev_close), abs(low - self.prev_close)) / close
        vol = max(0.8 * self.state.volatility + 0.2 * true_range, 1e-7)
        innovation = (ret - self.state.return_mean) / vol
        # Change-rate proxy: large normalized innovations increase the update rate.
        self.state.change_score = 0.85 * self.state.change_score + 0.15 * abs(innovation)
        self.state.detected = abs(innovation) * self.state.gain > self.state.criterion
        if self.state.detected:
            self.state.evidence = 0.0
            self.state.integration_window = 2.0
            self.state.alpha = min(0.65, max(0.20, self.state.alpha * 1.35))
        else:
            self.state.integration_window = min(96.0, max(3.0, 2.0 / max(self.state.alpha, 1e-6)))
            self.state.alpha = max(0.025, min(0.35, 0.995 * self.state.alpha + 0.005 / self.state.integration_window))

        # Estimate block: update the latent return state with adaptive UE.
        self.state.return_mean += self.state.alpha * (ret - self.state.return_mean)
        self.state.volatility = vol
        self.state.estimate = close * (1.0 + self.state.return_mean)
        self.state.evidence += self.state.return_mean / vol
        self.state.samples += 1
        self.prev_close = close
        self.prev_estimate = self.state.estimate
        self.last_observation = close
        return self.state

    def feedback(self, realized_return: float, action: int) -> None:
        """Update slow rule knowledge from an observed action outcome."""
        if action == 0:
            return
        correct = action * realized_return > 0
        target = 0.45 if correct else -0.45
        self.state.gain = max(0.25, min(3.0, self.state.gain + 0.02 * (target - (self.state.gain - 1.0))))
        if not correct:
            self.state.criterion = min(4.5, self.state.criterion + 0.02)
        else:
            self.state.criterion = max(1.2, self.state.criterion - 0.005)

    def snapshot(self) -> dict:
        return self.state.to_dict()


def build_model(state: Optional[dict] = None) -> EURUSDRealityModel:
    return EURUSDRealityModel(state)


__all__ = ["EURUSDRealityModel", "RealityState", "build_model"]


if __name__ == "__main__":
    print("EURUSDRealityModel ready; feed OHLC bars through update().")
